name: Deploy to Ec2
on:
  push:
    branches:
      - deploy-to-ec2
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Project
        run: gradle bootjar -x test
  Deploy:
    needs: Build
    runs-on: self-hosted
    steps:
      - name: Deploy to server
        env:
          HOST_NAME: ec2-18-142-246-131.ap-southeast-1.compute.amazonaws.com
          USER_NAME: ec2-user
          PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -T -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "./deploy.sh"
#          git checkout deploy-to-ec2
#          git fetch --all
#          git reset --hard origin/deploy-to-ec2
#          git pull origin deploy-to-ec2
#          gradle bootjar -x test
#          java -jar build/libs/IDP-0.0.1-SNAPSHOT.jar
