name: Deploy to Ec2
on:
  push:
    branches:
      - deploy-to-ec2
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Project
        run: gradle bootjar -x test
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        env:
          HOST_NAME: ec2-13-250-106-124.ap-southeast-1.compute.amazonaws.com
          USER_NAME: ec2-user
          PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
          scp build/libs/*.jar ${USER_NAME}@${HOST_NAME}:/home/ec2-user/app.jar
          java -jar app.jar '
