name: Deploy to Ec2
on:
  push:
    branches:
      - deploy-to-ec2
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Project
        run: gradle bootjar -x test
      - name: Execute Jar File
        run: sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar