name: Deploy to Ec2
on:
  push:
    branches:
      - deploy-to-ec2
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Project
        run: gradle bootjar -x test
      - name: Show path Jar
        run: pwd
      - name: Connect ssh to Ec2
        run: ssh ec2-user@13.250.106.124
      - name: Copy Jar file to Server Ec2
        run: scp build/libs/*.jar ec2-user@13.250.106.124:/home/ec2-user

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ec2-13-250-106-124.ap-southeast-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SERVER_KEY }}
          scrip:
            gradle bootjar -x test